name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: linux
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: linux
        path: target/release/buster
    - name: windows
      run: rustup target add x86_64-pc-windows-msvc && cargo build --release --target x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v4
      with:
        name: windows
        path: target/release/buster.exe    
